"use client";
import { useMemo, useState } from "react";
import { FileIcon, LayersIcon, SearchIcon, TrashIcon } from "@/components/Icons";
export type ScopeDocument = { id: string; name: string; selected: boolean; chunks?: number };

export default function DocumentScope({ documents, onToggle, onSelectAll, onDelete, placement = "up" }: { documents: ScopeDocument[]; onToggle: (id: string) => void; onSelectAll: () => void; onDelete: (id: string) => void; placement?: "up" | "down" }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const selected = documents.filter((doc) => doc.selected).length; const filtered = useMemo(() => documents.filter((doc) => doc.name.toLowerCase().includes(query.toLowerCase())), [documents, query]);
  if (!documents.length) return null;
  return <div className="relative"><button onClick={() => setOpen((value) => !value)} className="flex items-center gap-2 rounded-xl border border-signal/35 bg-white px-3 py-2 text-sm font-medium text-slate shadow-sm transition hover:border-signal"><LayersIcon className="h-4 w-4 text-signal" /><span className="hidden sm:inline">Retrieval</span>{selected}/{documents.length}<span className="text-slate/40">⌃</span></button>{open && <div className={`absolute z-40 w-[min(430px,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-slate/15 bg-white shadow-2xl ${placement === "up" ? "bottom-[calc(100%+10px)] left-0" : "right-0 top-[calc(100%+10px)]"}`}><div className="flex items-center justify-between border-b border-slate/10 px-4 py-3"><span className="text-xs font-bold uppercase tracking-[.12em] text-slate/55">Your document library</span><button onClick={onSelectAll} className="text-xs font-semibold text-signal">{selected === documents.length ? "Clear all" : "Query all"}</button></div><label className="relative m-3 block"><SearchIcon className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate/40" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search all uploaded documents" className="w-full rounded-xl border border-slate/15 bg-parchment py-2.5 pl-9 pr-3 text-sm outline-none focus:border-signal" /></label><div className="max-h-60 overflow-y-auto px-2 pb-2">{filtered.length ? filtered.map((doc) => <div key={doc.id} className="group flex items-center gap-3 rounded-xl px-3 py-2.5 hover:bg-parchment"><input type="checkbox" checked={doc.selected} onChange={() => onToggle(doc.id)} className="h-4 w-4 accent-signal" aria-label={`Use ${doc.name} for retrieval`} /><FileIcon className="h-4 w-4 shrink-0 text-signal" /><span className="min-w-0 flex-1 truncate text-sm text-slate">{doc.name}</span>{doc.chunks && <span className="text-xs text-slate/45">{doc.chunks} ch</span>}<button onClick={() => onDelete(doc.id)} className="rounded-md p-1 text-slate/35 opacity-0 transition hover:bg-red-50 hover:text-red-500 group-hover:opacity-100" aria-label={`Delete ${doc.name}`}><TrashIcon className="h-4 w-4" /></button></div>) : <p className="px-3 py-7 text-center text-sm text-slate/45">No documents found.</p>}</div><p className="border-t border-slate/10 px-4 py-2.5 text-xs text-slate/45">Select documents QueryMind may use for your next answer.</p></div>}</div>;
}
